# Site
name: "Indrajeet Gour"
title: "Indrajeet Gour"
description: "Create, Learn and Grow..."
logo: "assets/images/favicon-32x32.png"
favicon: "assets/images/favicon-32x32.png"
baseurl: ""
google_analytics: ""
disqus: "indrajeetgour"
mailchimp-list: ""
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  igour:
    name: Indrajeet Gour
    display_name: Indrajeet Gour
    gravatar: ijgour
    email: ijgour@gmail.com
    web: https://indrajeetgour.github.io
    twitter: https://twitter.com/ijgour
    description: "An Data Engineer who loves to work share the ideas of Big data, Cloud and other technologies."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
